---

- name: etckeeper first
  apt:
    cache_valid_time: 7200
    name:
      - etckeeper

- name: ensure keyrings folder exists
  file:
    dest: /etc/apt/keyrings
    state: directory
    mode: 0755

- name: basic packages from upstream
  apt:
    cache_valid_time: 7200
    autoclean: true
    autoremove: true
    update_cache: true
    name:
      - alien
      - apt-file
      - apt-rdepends
      - apt-transport-https
      - arp-scan
      - at
      - atop
      - autofs
      - autossh
      - barrier
      - bash-completion
      # - bashdb  ## https://sourceforge.net/projects/bashdb/files/bashdb/4.4-0.93/ ## not available in 18.04 yet
      - bfs
      - bison
      - bwm-ng
      - byobu
      - bzr
      - ccze
      - checkinstall
      - chrony
      - cifs-utils
      - cmake
      - colordiff
      - conntrack
      - cpanminus
      - curl
      - desktop-file-utils
      - dhcpdump
      - dhcping
      - dialog
      - diffutils
      - dnsmasq
      - dnsmasq-utils
      - docutils-common
      - edac-utils
      - elinks
      - ethstatus
      - evince
      - evolution
      - evolution-ews
      - exfat-fuse
      - expect
      - ext4magic
      - fail2ban
      - fd-find
      - filezilla
      - finger
      - fio
      - firewall-applet
      - firewall-config
      - firewalld
      - flex
      - flex-doc
      - fortunes
      - fortunes-off
      # - freerdp-x11
      - geoip-bin
      - git-all
      - global
      - graphviz
      - grepcidr
      - haveged
      - hdparm
      - hping3
      - html-xml-utils
      - htop
      - httping
      - iftop
      - inotify-tools
      - inxi
      - ioping
      - iotop
      - ipcalc
      - iperf3
      - ipmitool
      - iptraf-ng
      - iputils-arping
      - java-package
      - jq
      - kdiff3
      - l3afpad
      - ldnsutils
      - lft
      - lftp
      - libinput-tools
      - libpcap-dev
      - libreoffice
      - libsource-highlight-common
      - libxml2-utils
      - linux-tools-generic
      - lnav
      - ltrace
      - lynx
      - mbuffer
      - mc
      - meld
      - mlocate
      - moreutils
      - most
      - multitail
      - mysql-client
      - mytop
      - ncdt
      - ncdu
      - neofetch
      - net-tools
      - network-manager-fortisslvpn-gnome
      - network-manager-openvpn
      - ngrep
      - nicstat
      - nikto
      - nload
      - nmap
      - nmon
      - nomacs
      - ntfs-3g
      - nttcp
      - nuttcp
      - oathtool
      - onedrive
      - openvpn
      - p7zip-full
      - p7zip-rar
      - parallel
      - parted
      - patchutils
      - pbzip2
      - pcmanfm
      - percol
      - percona-toolkit
      - pgpdump
      - powertop
      - puppet-lint
      - pv
      - pwgen
      - python3.10-venv
      - python3-ipdb
      - python3-pip
      - python3-pudb
      - python3-rope
      - qalc
      - qmmp
      - rclone  ## https://rclone.org/onedrive/
      - rclone-browser
      - remmina
      - rename
      - ripgrep
      - rlwrap
      - rpm2cpio
      - rsync
      - ruby-ronn
      - rxvt-unicode
      - scite
      - screen
      - screenfetch
      - shellcheck
      - siege
      - sipcalc
      - smb4k
      - sngrep
      - snmp
      - snmp-mibs-downloader
      - sqlite3
      - source-highlight
      - stow
      - strace
      - subversion
      - sysstat
      - tack
      - tcpdump
      - thc-ipv6
      - thunderbird
      - thunderbird-locale-de
      - tig
      - tldr
      - tmux
      - traceroute
      - tree
      - tsung
      - tudu
      - units
      - uptimed
      - util-linux
      - vifm
      - vim
      - vim-syntastic
      - w3m
      - wdiff
      - wget
      - whois
      - whowatch
      - wireguard
      - x2x
      - xautomation
      - xbindkeys
      - xbindkeys-config
      - xdotool
      - xmlstarlet
      - xserver-xorg-input-synaptics
      - xserver-xorg-input-libinput
      - yamllint
      - yapf3
      - zmap

- name: no ufw allowed here
  apt:
    name: ufw
    state: absent

- name: make sure firewalld uses iptables as backend, because nftables breaks shit
  lineinfile:
    path: /etc/firewalld/firewalld.conf
    regex: '^FirewallBackend='
    line: 'FirewallBackend=iptables'

- name: language packages
  apt:
    cache_valid_time: 7200
    name:
      - aspell-de
      - hunspell-de-de
      - hyphen-de
      - ingerman
      - language-pack-de
      - language-pack-de-base
      - language-pack-gnome-de
      - language-pack-gnome-de-base
      - language-pack-kde-de
      - libreoffice-help-de
      - libreoffice-l10n-de
      - mythes-de
