---

- name: mask systemd-timesyncd
  systemd:
    name: systemd-timesyncd
    state: stopped
    enabled: false

- name: make chrony great again
  systemd:
    name: chrony
    state: started
    enabled: true
