---

- name: mask systemd-timesyncd
  systemd:
    name: systemd-timesyncd
    state: stopped
    enabled: no

- name: make chrony great again
  systemd:
    name: chrony
    state: started
    enabled: yes
