---

# https://unix.stackexchange.com/questions/13751/kernel-inotify-watch-limit-reached
# couldnt be bothered to read up sources for now, but kernel docs are lacking...
- name: increase global inotify limits
  sysctl:
    name: fs.inotify.max_user_watches
    value: "524288"
  changed_when: false

- name: increase user inotify limits
  sysctl:
    name: user.max_inotify_watches
    value: "16384"
  changed_when: false

- name: fuck off, swapspace
  sysctl:
    name: vm.swappiness
    value: "0"
  changed_when: false

- name: make iotop(1) work again
  sysctl:
    name: kernel.task_delayacct
    value: 1
  changed_when: false
