---

- name: check /etc/rc.local existence
  stat:
    path: /etc/rc.local
  register: rc_local_stat
  changed_when: false

- name: create /etc/rc.local if needed
  copy:
    src: rc.local
    dest: /etc/rc.local
    owner: root
    group: root
    mode: 0700
  when: not rc_local_stat.stat.exists

- name: deploy rc-local unit file
  copy:
    src: rc-local.service
    dest: /etc/systemd/system/

- name: systemd daemon reload
  systemd:
    daemon_reload: yes

- name: enable and start systemd service
  systemd:
    name: rc-local.service
    state: restarted
  changed_when: false

