---

- name: check if baloo is disabled
  become: true
  become_user: sjas
  shell:
    cmd: balooctl status
    executable: /bin/bash
  register: exitcode_baloo_check
  ignore_errors: true
  changed_when: false

- name: disable baloo
  become: true
  become_user: sjas
  command: balooctl disable
  when: exitcode_baloo_check.rc == 0
  changed_when: false

- name: delete baloo index
  become: true
  become_user: sjas
  command: balooctl purge
  when: exitcode_baloo_check.rc == 0
  changed_when: false

- name: dont let baloo do contentindexing
  become: true
  become_user: sjas
  command: balooctl config set contentIndexing no
  when: exitcode_baloo_check.rc == 0
  ignore_errors: true

- name: kill baloo_file process if existing
  become: true
  become_user: sjas
  command: pkill -kill baloo_file
  when: exitcode_baloo_check.rc == 0
  ignore_errors: true

- name: kill baloorunner  processes if existing
  become: true
  become_user: sjas
  command: pkill -kill baloorunner
  when: exitcode_baloo_check.rc == 0
  ignore_errors: true
