---

- name: check if baloo is disabled
  shell: 2>&1 balooctl status | grep 'Baloo is currently disabled. To enable, please run balooctl enable'
  register: exitcode_baloo_check
  ignore_errors: true
  changed_when: false

- name: disable baloo
  command: balooctl disable
  changed_when: false

- name: delete baloo index
  command: balooctl purge
  when: exitcode_baloo_check.rc != 0
  changed_when: false

- name: dont let baloo do contentindexing
  command: balooctl config set contentIndexing no
  when: exitcode_baloo_check.rc != 0
  changed_when: false

- name: kill baloo_file process if existing
  shell: 'pkill -kill baloo_file||:'
  when: exitcode_baloo_check.rc != 0
  changed_when: false

- name: kill baloorunner  processes if existing
  shell: 'pkill -kill baloorunner||:'
  when: exitcode_baloo_check.rc != 0
  changed_when: false
