---

- name: ensure autostart folder exists
  become: true
  become_user: sjas
  file:
    dest: /home/sjas/.config/autostart
    state: directory

# - name: shutter autostart
#   become: true
#   become_user: sjas
#   copy:
#     src: shutter.desktop
#     dest: /home/sjas/.config/autostart/shutter.desktop
