---

# https://askubuntu.com/questions/213680/how-to-restart-kwin-when-it-is-hung
- name: fix taskbar size
  replace:
    path: /home/sjas/.config/plasmashellrc
    regexp: "^thickness=.*"
    replace: "thickness=68"
  notify: kwin_reload
