---

- name: rustup install check
  become: yes
  become_user: sjas
  shell: find /home/sjas/.cargo/bin/ -type f | grep rustup
  register: exitcode_rustup_install
  ignore_errors: true
  changed_when: false

- name: install rustup
  become: yes
  become_user: sjas
  shell: "curl https://sh.rustup.rs -sSf | sh -s -- -y"
  when: exitcode_rustup_install.rc != 0
  tags: skip_ansible_lint

- name: rustup update
  become: yes
  become_user: sjas
  command: "/home/sjas/.cargo/bin/rustup update"
  changed_when: false

- name: fix cargo error message when cant source the env (for root user)
  lineinfile:
    path=/home/sjas/.bashrc
    regexp='. "\$HOME/.cargo/env"$'
    line='. "/home/sjas/.cargo/env"'
