---

- name: install libvirt and virt-manager packages
  apt:
    cache_valid_time: 7200
    name:
      - libguestfs-tools
      - libosinfo-bin
      - unrar-free
      - virt-manager
      - virt-top
      - virt-what
      - virtinst

- name: ensure libvirtd group exists
  group:
    name: libvirtd

- name: make user part of libvirtd group
  user:
    name: sjas
    append: true
    groups: libvirtd

- name: change default network 1
  replace:
    regexp: '192.168.122'
    replace: '172.16.172'
    dest: /etc/libvirt/qemu/networks/default.xml
