---

- name: nextcloud desktop client via snap
  snap:
    name: keepassxc

- name: enable browser integration
  become: true
  become_user: sjas
  ini_file:
    path: /home/sjas/snap/keepassxc/current/.config/keepassxc/keepassxc.ini
    create: true
    mode: 0664
    no_extra_spaces: true
    section: Browser
    option: Enabled
    value: true
