---

# https://blog.cloudflare.com/three-little-tools-mmsum-mmwatch-mmhistogram/
# https://github.com/cloudflare/cloudflare-blog/tree/master/2017-06-29-ssdp
- name: deploy CF mm tools
  become: true
  become_user: sjas
  copy: src={{ item }} dest=/home/sjas/.local/bin mode=0744
  with_items:
    - mmhistogram
    - mmsum
    - mmwatch
