---

# spectacle already preinstalled
- name: install screenshot packages
  apt:
    cache_valid_time: 7200
    name:
      - shutter

## shutter config ###########################################################################################
# this is yucky because its not in ~/.config and using xml instead of ini files ..
# no its not if you can speak xpath
# manually this could look like this:
#
# xmlstarlet edit --inplace --update "/opt/general[@filename]/@filename" --value "asdf" ~/.shutter/settings.xml
# xpath -e '/opt/general/@filename' ~/.shutter/settings.xml
#
# Found 1 nodes in /home/sjas/.shutter/settings.xml:
# -- NODE --
#  filename="asdf"
#
# also:
# https://peteris.rocks/blog/modifying-xml-json-ini-configuration-files-without-sed/
#
- name: shutter
  become: true
  become_user: sjas
  xml:
    path: /home/sjas/.shutter/settings.xml
    xpath: /opt/general[@filename]
    attribute: filename
    value: shutter_$name_%NNN_%Y%m%d_%T

## spectacle config #########################################################################################
- name: spectacle spectaclerc
  become: true
  become_user: sjas
  ini_file:
    path: /home/sjas/.config/spectaclerc
    create: true
    mode: 0664
    no_extra_spaces: true
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: "", option: "", value: "" }
    - { section: "General", option: "clipboardGroup", value: "PostScreenshotCopyImage" }
    - { section: "General", option: "autoSaveImage", value: "true" }
    - { section: "General", option: "onLaunchAction", value: "UseLastUsedCapturemode" }
    - { section: "General", option: "rememberLastRectangularRegion", value: "UntilSpectacleIsClosed" }
    - { section: "General", option: "showCaptureInstructions", value: "false" }
    - { section: "General", option: "useReleaseToCapture", value: "true" }
    - { section: "GuiConfig", option: "captureMode", value: "5" }
    - { section: "GuiConfig", option: "quitAfterSaveCopyExport", value: "true" }
    - { section: "Save", option: "saveFilenameFormat", value: "spectacle_%Y%M%D_%H%m%S" }

- name: spectacle plasmanotify
  become: true
  become_user: sjas
  ini_file:
    path: /home/sjas/.config/plasmanotifyrc
    create: true
    mode: 0664
    no_extra_spaces: true
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: "Applications][org.kde.spectacle", option: "ShowBadges", value: "false" }
    - { section: "Applications][org.kde.spectacle", option: "ShowInHistory", value: "false" }
    - { section: "Applications][org.kde.spectacle", option: "ShowPopups", value: "false" }
