---

# spectacle already preinstalled
- name: install screenshot packages
  apt:
    cache_valid_time: 7200
    name:
      - shutter

# - name: spectacle
#   become: true
#   become_user: sjas
#   ini_file:
#     path: /home/sjas/.config/
#     create: true
#     mode: 0664
#     no_extra_spaces: true
#     section:
#     option:
#     value:
#
# - name: shutter
#   become: true
#   become_user: sjas
#   ini_file:
#     path: /home/sjas/.config/
#     create: true
#     mode: 0664
#     no_extra_spaces: true
#     section:
#     option:
#     value:

## shutter config ###########################################################################################
# this is yucky because its not in ~/.config and using xml instead of ini files ..
# no its not if you can speak xpath
# manually this could look like this:
#
# xmlstarlet edit --inplace --update "/opt/general[@filename]/@filename" --value "asdf" ~/.shutter/settings.xml
# xpath -e '/opt/general/@filename' ~/.shutter/settings.xml
#
# Found 1 nodes in /home/sjas/.shutter/settings.xml:
# -- NODE --
#  filename="asdf"
#
# also:
# https://peteris.rocks/blog/modifying-xml-json-ini-configuration-files-without-sed/
#
# fixme
# - name: shutter
#   become: true
#   become_user: sjas
#   xml:
#     path: /home/sjas/.shutter/settings.xml
#     xpath: /opt/general[@filename]
#     attribute: filename
#     value: shutter_$name_%NNN_%Y%m%d_%T

## spectacle config #########################################################################################
- name: spectacle copy to clipboard automatically
  become: true
  become_user: sjas
  ini_file:
    path: /home/sjas/.config/spectaclerc
    create: true
    mode: 0664
    no_extra_spaces: true
    section: General
    option: clipboardGroup
    value: PostScreenshotCopyImage

- name: spectacle autosave image
  become: true
  become_user: sjas
  ini_file:
    path: /home/sjas/.config/spectaclerc
    create: true
    mode: 0664
    no_extra_spaces: true
    section: General
    option: autoSaveImage
    value: true

- name: spectacle use last used capture method
  become: true
  become_user: sjas
  ini_file:
    path: /home/sjas/.config/spectaclerc
    create: true
    mode: 0664
    no_extra_spaces: true
    section: General
    option: onLaunchAction
    value: UseLastUsedCapturemode

- name: spectacle remember region only until spectacle closes
  become: true
  become_user: sjas
  ini_file:
    path: /home/sjas/.config/spectaclerc
    create: true
    mode: 0664
    no_extra_spaces: true
    section: General
    option: rememberLastRectangularRegion
    value: UntilSpectacleIsClosed

- name: spectacle no nagging
  become: true
  become_user: sjas
  ini_file:
    path: /home/sjas/.config/spectaclerc
    create: true
    mode: 0664
    no_extra_spaces: true
    section: General
    option: showCaptureInstructions
    value: false

- name: spectacle capture on release
  become: true
  become_user: sjas
  ini_file:
    path: /home/sjas/.config/spectaclerc
    create: true
    mode: 0664
    no_extra_spaces: true
    section: General
    option: useReleaseToCapture
    value: true

- name: spectacle selection capturing
  become: true
  become_user: sjas
  ini_file:
    path: /home/sjas/.config/spectaclerc
    create: true
    mode: 0664
    no_extra_spaces: true
    section: GuiConfig
    option: captureMode
    value: 5

- name: spectacle quit after save/copy/export
  become: true
  become_user: sjas
  ini_file:
    path: /home/sjas/.config/spectaclerc
    create: true
    mode: 0664
    no_extra_spaces: true
    section: GuiConfig
    option: quitAfterSaveCopyExport
    value: true

- name: spectacle filename format
  become: true
  become_user: sjas
  ini_file:
    path: /home/sjas/.config/spectaclerc
    create: true
    mode: 0664
    no_extra_spaces: true
    section: Save
    option: saveFilenameFormat
    value: spectacle_%Y%M%D_%H%m%S

- name: spectacle noshowbadges
  become: true
  become_user: sjas
  ini_file:
    path: /home/sjas/.config/plasmanotifyrc
    create: true
    mode: 0664
    no_extra_spaces: true
    section: Applications][org.kde.spectacle
    option: ShowBadges
    value: false

- name: spectacle noshowinhistory
  become: true
  become_user: sjas
  ini_file:
    path: /home/sjas/.config/plasmanotifyrc
    create: true
    mode: 0664
    no_extra_spaces: true
    section: Applications][org.kde.spectacle
    option: ShowInHistory
    value: false

- name: spectacle noshowpopups
  become: true
  become_user: sjas
  ini_file:
    path: /home/sjas/.config/plasmanotifyrc
    create: true
    mode: 0664
    no_extra_spaces: true
    section: Applications][org.kde.spectacle
    option: ShowPopups
    value: false
