---

- name: microsoft apt signing key
  apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present
    keyring: /etc/apt/trusted.gpg.d/microsoft.gpg

- name: teams repo
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main
    state: present
    filename: teams

- name: install teams
  apt:
    name: teams
    state: latest
    update_cache: true

- name: teams mime type
  become_user: sjas
  ini_file:
    path: /home/sjas/.config/mimeapps.list
    create: false
    no_extra_spaces: true
    section: Default Applications
    option: x-scheme-handler/msteams
    value: teams.desktop
