---

- name: terminator package
  apt:
    name: terminator
    cache_valid_time: 7200

- name: terminator config folder
  become: true
  become_user: sjas
  file:
    dest: /home/sjas/.config/terminator/
    state: directory
    mode: 0775

- name: terminator config
  become: true
  become_user: sjas
  copy:
    src: config
    dest: /home/sjas/.config/terminator/
    mode: 0664

- name: ensure terminator ensure plugin folder exists
  become: true
  become_user: sjas
  file:
    dest: /home/sjas/.config/terminator/plugins/
    state: directory
    mode: 0775

# # - name: install missing packages for plugins
# #   apt:
# #     name: "{{item}}"
# #   loop:
# #     - python-vte
# #     - python-gobject
#
# - name: deploy terminator plugins
#   become: true
#   become_user: sjas
#   copy:
#     src: "{{ item }}"
#     dest: /home/sjas/.config/terminator/plugins/
#     mode: 0755
#   loop:
#     - dump_to_file.py
#     - clone_session.py
#     - clisnips.py
#     - clisnips_plugin.py
#
# - name: deploy clisnips files
#   become: true
#   become_user: sjas
#   copy:
#     src: /home/sjas/etc/.ansible/roles/terminals/files/clisnips
#     dest: /home/sjas/.config/terminator/plugins/
#     mode: 0755
#     remote_src: true
#
# - name: deploy clisnips dbus service file
#   copy:
#     src: org.ju1ius.CliSnips.service
#     dest: /usr/share/dbus-1/services/
#     mode: 0664
