---

- name: xterm packages
  apt:
    cache_valid_time: 7200
    name:
      - xterm
      - xtermcontrol
      - xtermset

- name: make sure .Xdefaults is present
  become: yes
  become_user: sjas
  file:
    dest: /home/sjas/.Xdefaults
    state: touch
  changed_when: false

- name: make xterm shortcuts behave
  become: yes
  become_user: sjas
  lineinfile: dest=/home/sjas/.Xdefaults line="xterm*metaSendsEscape:true"
