---

- name: check if ghostty is already installed
  stat:
    path: /usr/bin/ghostty
  register: ghostty_installed
  changed_when: false

- name: register current ghostty version
  shell: "/usr/bin/ghostty --version|grep -- '- version:'|awk '{print $NF}'"
  register: ghostty_installed_version
  when: ghostty_installed.stat.exists
  changed_when: false

- name: register lastest ghostty upstream version
  community.general.github_release:
    user: mkasberg
    repo: ghostty-ubuntu
    action: latest_release
  register: latest_ghostty_release_version
  changed_when: false

- name: register latest ghostty upstream version in short for comparison
  shell: "/bin/echo {{ latest_ghostty_release_version.tag }} | sed 's/-.*//'"
  register: latest_ghostty_release_version_short
  when: ghostty_installed.stat.exists
  changed_when: false

- name: register ubuntu version
  shell: "grep VERSION_ID /etc/os-release|cut -d= -f2|sed 's/\"//g'"
  register: ubuntu_version
  when: not ghostty_installed.stat.exists or (ghostty_installed_version.stdout != ghostty_installed_version.stdout)
  changed_when: false

- name: register latest ghostty release name
  shell: "/bin/echo ghostty_{{ latest_ghostty_release_version.tag }}_amd64_{{ ubuntu_version.stdout }}.deb | /bin/sed 's/-\\(ppa1\\)/.\\1/'"
  register: ghostty_latest_release_fullname
  when: not ghostty_installed.stat.exists or (ghostty_installed_version.stdout != ghostty_installed_version.stdout)
  changed_when: false

- name: download current ghostty version
  get_url:
    url: "https://github.com/mkasberg/ghostty-ubuntu/releases/download/{{ latest_ghostty_release_version.tag }}/{{ ghostty_latest_release_fullname      .stdout }}"
    dest: "/tmp"
  when: not ghostty_installed.stat.exists or (ghostty_installed_version.stdout != ghostty_installed_version.stdout)

- name: install ghostty
  apt:
    deb: "/tmp/{{ ghostty_latest_release_fullname.stdout }}"
  when: not ghostty_installed.stat.exists or (ghostty_installed_version.stdout != ghostty_installed_version.stdout)

- name: cleanup .deb file
  file:
    path: "/tmp/{{ ghostty_latest_release_fullname.stdout }}"
    state: absent
  when: not ghostty_installed.stat.exists or (ghostty_installed_version.stdout != ghostty_installed_version.stdout)

- name: ghostty config folder
  become: true
  become_user: sjas
  file:
    dest: /home/sjas/.config/ghostty/
    state: directory
    mode: 0775

- name: ghostty config
  become: true
  become_user: sjas
  copy:
    src: config_ghostty
    dest: /home/sjas/.config/ghostty/config
    mode: 0664
