---

- name: terminator
  import_tasks: 0x01_terminator.yml
  tags: terminals,terminator

- name: xterm
  import_tasks: 0x02_xterm.yml
  tags: terminals,xterm

- name: tmux bindings
  import_tasks: 0x03_tmux.yml
  tags: terminals,tmux

- name: ghostty
  import_tasks: 0x04_ghostty.yml
  tags: terminals,ghostty
