---

- name: reference configs from .bashrc
  lineinfile:
    path: /home/sjas/.bashrc
    line: '. /home/sjas/etc/.ansible/roles/0x02_shells/files/{{ item }}'
  with_items:
    - .bashrc_env
    - .bashrc_aliases
    - .bashrc_git
    - .bashrc_completion

- name: get a unlimited history
  lineinfile:
    path: /home/sjas/.bashrc
    regex: 'HIST.*SIZE'
    state: absent

- name: fortune
  lineinfile:
    path: /home/sjas/.bashrc
    line: 'echo "$-"|grep -q i&&fortune -o -s'

- name: reference .bashrc_includes if present
  lineinfile:
    path: /home/sjas/.bashrc
    line: "[[ -f /home/sjas/etc/.dotfiles/.bashrc_includes ]]&&. /home/sjas/etc/.dotfiles/.bashrc_includes||:"

- name: check the current root .bashrc file/symlink
  stat:
    path: /root/.bashrc
  register: root_bashrc_exists
  changed_when: false

- name: remove it if current root .bashrc is not a symlink
  file:
    path: /root/.bashrc
    state: absent
  when: root_bashrc_exists.stat.exists and not root_bashrc_exists.stat.islnk

- name: symlink .bashrc for root
  file:
    dest: /root/.bashrc
    src: /home/sjas/.bashrc
    state: link

- name: check the current root .vimrc file/symlink
  stat:
    path: /root/.vimrc
  register: root_vimrc_exists
  changed_when: false

- name: remove it if current root .vimrc is not a symlink
  file:
    path: /root/.vimrc
    state: absent
  when: root_vimrc_exists.stat.exists and not root_vimrc_exists.stat.islnk

- name: symlink .vimrc for root
  file:
    dest: /root/.vimrc
    src: /home/sjas/.vimrc
    state: link

- name: check the current root .ssh file/symlink
  stat:
    path: /root/.ssh
  register: root_ssh_exists
  changed_when: false

- name: remove if current root .ssh is not a symlink
  file:
    path: /root/.ssh
    state: absent
  when: root_ssh_exists.stat.exists and not root_ssh_exists.stat.islnk

- name: symlink .ssh for root
  file:
    dest: /root/.ssh
    src: /home/sjas/.ssh
    state: link

- name: mc config
  become: true
  become_user: sjas
  copy:
    src: "{{ item }}"
    dest: /home/sjas/.config/mc/
    mode: 0644
  with_items:
    - ini
    - panels.ini
    - mc.ext  ## this fixes enter to be able to open files!!!

- name: ensure .config folder exists for root user
  file:
    dest: /root/.config
    state: directory
    mode: 0755

- name: mc folder link for root user
  file:
    dest: /root/.config/mc
    src: /home/sjas/.config/mc
    state: link

- name: deploy iptables colorize script
  become: true
  become_user: sjas
  copy:
    src: colorize_iptables_output.sh
    dest: /home/sjas/.local/bin
    mode: 0775

- name: deploy shfmt
  become: true
  become_user: sjas
  copy:
    src: shfmt
    dest: /home/sjas/.local/bin
    mode: 0775

- name: deploy stats script
  become: true
  become_user: sjas
  copy:
    src: stats
    dest: /home/sjas/.local/bin
    mode: 0775

- name: deploy .infokey
  become: true
  become_user: sjas
  copy:
    src: .infokey
    dest: /home/sjas/
    mode: 0664

- name: deploy .lesskey
  become: true
  become_user: sjas
  copy:
    src: .lesskey
    dest: /home/sjas/
    mode: 0664

- name: deploy .dialogrc
  become: true
  become_user: sjas
  copy:
    src: .dialogrc
    dest: /home/sjas/
    mode: 0664

- name: deploy yaml langfile for less highlighing
  copy:
    src: yaml.lang
    dest: /usr/share/source-highlight/
    mode: 0644

- name: link yaml.lang
  lineinfile:
    path: /usr/share/source-highlight/lang.map
    line: '{{ item }}'
  with_items:
    - yaml = yaml.lang
    - yml = yaml.lang
