---

- name: microsoft apt-key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
    keyring: /etc/apt/keyrings/microsoft.gpg

- name: microsoft powershell repo
  apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/ubuntu/24.04/prod noble main
    state: present
    filename: powershell

- name: install powershell package
  apt:
    name: powershell
    state: present
    update_cache: true
