---

- name: microsoft apt-key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
    keyring: /etc/apt/trusted.gpg.d/microsoft.gpg

- name: microsoft powershell repo
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/ubuntu/22.04/prod jammy main
    state: present
    filename: powershell

- name: install powershell package
  apt:
    name: powershell
    state: present
    update_cache: true
