---

- name: reference configs from .bashrc
  lineinfile: path=/home/sjas/.bashrc line='. /home/sjas/etc/.ansible/roles/shells/files/{{ item }}'
  with_items:
    - .bashrc_env
    - .bashrc_aliases
    - .bashrc_git
    - .bashrc_completion

- name: get a unlimited history
  lineinfile: path=/home/sjas/.bashrc regex='HIST.*SIZE' state=absent

- name: fortune
  lineinfile: path=/home/sjas/.bashrc line="echo "$-" | grep -q i && fortune -o -s"

- name: reference .bashrc_includes if present
  lineinfile: path=/home/sjas/.bashrc line="[[ -f /home/sjas/etc/.dotfiles/.bashrc_includes ]] && . /home/sjas/etc/.dotfiles/.bashrc_includes || :"

- name: mc def config def user
  become: yes
  become_user: sjas
  copy:
    src: "{{ item }}"
    dest: /home/sjas/.config/mc/
  with_items:
    - ini
    - panels.ini
    - mc.ext  ## this fixes enter to be able to open files!!!

- name: ensure .config/mc folder exists for root user
  file:
    dest: /root/.config/mc
    state: directory

- name: mc def config root user
  copy:
    src: "{{ item }}"
    dest: /root/.config/mc/
  with_items:
    - ini
    - panels.ini

- name: deploy iptables colorize script
  become: yes
  become_user: sjas
  copy:
    src: colorize_iptables_output.sh
    dest: /home/sjas/.local/bin
    mode: 0775

- name: deploy shfmt
  become: yes
  become_user: sjas
  copy:
    src: shfmt
    dest: /home/sjas/.local/bin
    mode: 0775

- name: deploy stats script
  become: yes
  become_user: sjas
  copy:
    src: stats
    dest: /home/sjas/.local/bin
    mode: 0775

- name: deploy .dialogrc
  become: yes
  become_user: sjas
  copy:
    src: .dialogrc
    dest: /home/sjas/
    mode: 0664

