---

- name: google apt-key
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    keyring: /etc/apt/trusted.gpg.d/google.gpg

- name: google-chrome repo
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    filename: chrome

- name: chrome dependencies
  apt:
    update_cache: true
    name:
      - fonts-liberation

- name: google-chrome package
  apt:
    name: google-chrome-stable
    cache_valid_time: 7200
