---

- name: get firefox profile folder path
  shell: ls /home/sjas/.mozilla/firefox/*default-release -d
  register: ff_path
  changed_when: false

- name: deploy firefox base settings
  become: true
  become_user: sjas
  copy:
    src: user.js
    dest: "{{ ff_path.stdout }}"
    mode: 0664

- name: remove obsolete directories
  file:
    dest: "{{ ff_path.stdout }}/chrome"
    state: absent
