---

- name: ff get profile folder path
  shell: ls /home/sjas/.mozilla/firefox/*default-release -d
  register: ff_path
  changed_when: false

- name: ff base settings
  become: true
  become_user: sjas
  copy:
    src: user.js
    dest: "{{ ff_path.stdout }}"
    mode: 0664

- name: ff remove obsolete directories
  file:
    dest: "{{ ff_path.stdout }}/chrome"
    state: absent

- name: ff default
  become: true
  become_user: sjas
  ini_file:
    path: /home/sjas/.config/mimeapps.list
    create: true
    mode: 0664
    no_extra_spaces: true
    section: Default Applications
    option: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: "text/html",                     value: "firefox.desktop" }
    - { key: "x-scheme-handler/http",         value: "firefox.desktop" }
    - { key: "x-scheme-handler/https",        value: "firefox.desktop" }
    - { key: "x-scheme-handler/chrome",       value: "firefox.desktop" }
    - { key: "application/x-extension-htm",   value: "firefox.desktop" }
    - { key: "application/x-extension-html",  value: "firefox.desktop" }
    - { key: "application/x-extension-shtml", value: "firefox.desktop" }
    - { key: "application/xhtml+xml",         value: "firefox.desktop" }
    - { key: "application/x-extension-xhtml", value: "firefox.desktop" }
    - { key: "application/x-extension-xht",   value: "firefox.desktop" }

- name: ff default, more associations
  become: true
  become_user: sjas
  ini_file:
    path: /home/sjas/.config/mimeapps.list
    create: true
    mode: 0664
    no_extra_spaces: true
    section: Added Associations
    option: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: "x-scheme-handler/http",         value: "firefox.desktop" }
    - { key: "x-scheme-handler/https",        value: "firefox.desktop" }
    - { key: "x-scheme-handler/chrome",       value: "firefox.desktop" }
    - { key: "text/html",                     value: "firefox.desktop" }
    - { key: "application/x-extension-htm",   value: "firefox.desktop" }
    - { key: "application/x-extension-html",  value: "firefox.desktop" }
    - { key: "application/x-extension-shtml", value: "firefox.desktop" }
    - { key: "application/xhtml+xml",         value: "firefox.desktop" }
    - { key: "application/x-extension-xhtml", value: "firefox.desktop" }
    - { key: "application/x-extension-xht",   value: "firefox.desktop" }

## extensions here we come ##################################################################################
- name: ff download and install extensions
  become: true
  become_user: sjas
  get_url:
    url: "https://addons.mozilla.org/firefox/downloads/latest/{{ item.key }}/latest.xpi"
    dest: "{{ ff_path.stdout }}/extensions/{{ item.value }}.xpi"
    mode: 0644
  with_items:
    - { key: 'brandon1024-find',            value: '{6fa42eda-38ca-4126-96d5-3163f0de6900}' }
    - { key: 'keepassxc-browser',           value: 'keepassxc-browser@keepassxc.org' }
    - { key: 'ublock-origin',               value: 'uBlock0@raymondhill.net' }
    - { key: 'cookie-autodelete',           value: 'CookieAutoDelete@kennydo.com' }
    - { key: 'screenshot-capture-annotate', value: 'jid0-GXjLLfbCoAx0LcltEdFrEkQdQPI@jetpack' }
    - { key: 'foxclocks',                   value: '{d37dc5d0-431d-44e5-8c91-49419370caa1}' }
    - { key: 'tron-legacy-beau-garrett',    value: '{b2d342ea-30a3-4a95-bf6b-a655c01ce1ad}' }
    - { key: 'localise-timezones',          value: '{a0da06f4-9f95-41f1-9e42-eb189dc8c758}' }
    - { key: 'timezonify',                  value: '{c9a5755e-2b16-41c1-a551-a79c7e98269f}' }
