---

# fuck this shit, the ppa doesnt work and ubutnu make doesnt update
# https://askubuntu.com/questions/548003/how-do-i-install-the-firefox-developer-edition

# # this doesnt work because there is no jammy release
# - name: mozilla apt signing key
#   apt_key:
#     keyserver: pgpkeys.mit.edu
#     id: EF4186FE247510BE
#     keyring: /etc/apt/trusted.gpg.d/mozilla.gpg
#
# - name: firefox developer edition repo
#   apt_repository:
#     repo: deb https://ppa.launchpadcontent.net/ubuntu-mozilla-daily/firefox-aurora/ubuntu/ jammy main
#     state: present
#     filename: firefox-developer-edition
#
# - name: firefox developer edition install
#   apt:
#     name: firefox
#     update_cache: true

- name: check if firefox developer edition is already installed
  stat:
    path: /opt/firefox
  register: firefox_installed
  changed_when: false

- name: uninstall ff snap if needed
  snap:
    name: firefox
    state: absent

- name: uninstall ff package if needed
  apt:
    name: firefox
    state: absent

- name: download ff dev ed
  get_url:
    url: https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=linux64&lang=en-US
    dest: /tmp/ff.tar.bz2
  when: not firefox_installed.stat.exists

- name: unarchive ff dev ed
  unarchive:
    src: /tmp/ff.tar.bz2
    dest: /opt
  when: not firefox_installed.stat.exists

- name: cleanup ff dev ed install files
  file:
    path: /tmp/ff.tar.bz2
    state: absent
  when: not firefox_installed.stat.exists

- name: ff dev ed .desktop file
  become: true
  become_user: sjas
  copy:
    src: firefox.desktop
    dest: /home/sjas/.local/share/applications/
    mode: 0644

- name: ff get profile folder path
  # shell: ls /home/sjas/.mozilla/firefox/*default-release -d  ##this is for the regular ff version not ff dev ed
  shell: ls /home/sjas/.mozilla/firefox/*.dev-edition-default -d
  register: ff_path
  changed_when: false

- name: ff base settings
  become: true
  become_user: sjas
  copy:
    src: user.js
    dest: "{{ ff_path.stdout }}"
    mode: 0664

- name: ff default
  become: true
  become_user: sjas
  ini_file:
    path: /home/sjas/.config/mimeapps.list
    create: true
    mode: 0664
    no_extra_spaces: true
    section: Default Applications
    option: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: "text/html",                     value: "firefox.desktop" }
    - { key: "x-scheme-handler/http",         value: "firefox.desktop" }
    - { key: "x-scheme-handler/https",        value: "firefox.desktop" }
    - { key: "x-scheme-handler/chrome",       value: "firefox.desktop" }
    - { key: "application/x-extension-htm",   value: "firefox.desktop" }
    - { key: "application/x-extension-html",  value: "firefox.desktop" }
    - { key: "application/x-extension-shtml", value: "firefox.desktop" }
    - { key: "application/xhtml+xml",         value: "firefox.desktop" }
    - { key: "application/x-extension-xhtml", value: "firefox.desktop" }
    - { key: "application/x-extension-xht",   value: "firefox.desktop" }

- name: ff default, more associations
  become: true
  become_user: sjas
  ini_file:
    path: /home/sjas/.config/mimeapps.list
    create: true
    mode: 0664
    no_extra_spaces: true
    section: Added Associations
    option: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: "x-scheme-handler/http",         value: "firefox.desktop" }
    - { key: "x-scheme-handler/https",        value: "firefox.desktop" }
    - { key: "x-scheme-handler/chrome",       value: "firefox.desktop" }
    - { key: "text/html",                     value: "firefox.desktop" }
    - { key: "application/x-extension-htm",   value: "firefox.desktop" }
    - { key: "application/x-extension-html",  value: "firefox.desktop" }
    - { key: "application/x-extension-shtml", value: "firefox.desktop" }
    - { key: "application/xhtml+xml",         value: "firefox.desktop" }
    - { key: "application/x-extension-xhtml", value: "firefox.desktop" }
    - { key: "application/x-extension-xht",   value: "firefox.desktop" }

## extensions here we come ##################################################################################
# - https://wiringbits.net/browser-extensions/2020/11/27/installing-unsigned-extensions-permanently-to-firefox.html
# - https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings

- name: ensure ff extension folder exists
  become: true
  become_user: sjas
  file:
    path: "{{ ff_path.stdout }}/extensions"
    state: directory
    mode: 0755

# get the id's via:
# about:config -> extensions.webextensions.uuids
- name: ff download and install extensions
  become: true
  become_user: sjas
  get_url:
    url: "https://addons.mozilla.org/firefox/downloads/latest/{{ item.key }}/latest.xpi"
    dest: "{{ ff_path.stdout }}/extensions/{{ item.value }}.xpi"
    mode: 0644
  with_items:
    - { key: 'brandon1024-find',            value: '{6fa42eda-38ca-4126-96d5-3163f0de6900}' }
    - { key: 'keepassxc-browser',           value: 'keepassxc-browser@keepassxc.org' }
    - { key: 'ublock-origin',               value: 'uBlock0@raymondhill.net' }
    - { key: 'cookie-autodelete',           value: 'CookieAutoDelete@kennydo.com' }
    - { key: 'screenshot-capture-annotate', value: 'jid0-GXjLLfbCoAx0LcltEdFrEkQdQPI@jetpack' }
    - { key: 'foxclocks',                   value: '{d37dc5d0-431d-44e5-8c91-49419370caa1}' }
    - { key: 'tron-legacy-beau-garrett',    value: '{b2d342ea-30a3-4a95-bf6b-a655c01ce1ad}' }
    - { key: 'localise-timezones',          value: '{a0da06f4-9f95-41f1-9e42-eb189dc8c758}' }
    - { key: 'timezonify',                  value: '{c9a5755e-2b16-41c1-a551-a79c7e98269f}' }
