---

- name: chromium
  include: 0x01_chromium.yml
  tags: browsers,chromium

- name: google-chrome
  include: 0x02_google-chrome.yml
  tags: browsers,chrome

- name: firefox
  include: 0x03_firefox.yml
  tags: browsers,firefox

- name: brave
  include: 0x04_brave.yml
  tags: browsers,brave

- name: microsoft edge
  include: 0x05_edge.yml
  tags: browsers,edge
