---

- name: install libvirt and virt-manager packages
  apt:
    cache_valid_time: 7200
    name:
      - qemu
      - qemu-utils
      - libguestfs-tools
      - libosinfo-bin
      - unrar-free
      - virt-manager
      - virt-top
      - virt-what
      - virtinst
  tags: virt

- name: ensure libvirtd group exists
  group:
    name: libvirtd
  tags: virt

- name: make user part of libvirtd group
  user:
    name: sjas
    append: yes
    groups: libvirtd
  tags: virt
