---

- name: hasklig install check
  shell: find /home/sjas/.fonts -type f | grep Hasklig
  register: exitcode_hasklig_install
  ignore_errors: true
  changed_when: false

- name: make sure .fonts folder exists
  become: yes
  become_user: sjas
  file:
    dest: /home/sjas/.fonts
    state: directory

- name: unarchive hasklig
  become: yes
  become_user: sjas
  unarchive:
    src: Hasklig-1.2.zip
    dest: /home/sjas/.fonts
  when: exitcode_hasklig_install.rc != 0
