---

- name: create /etc/rc.local
  copy:
    src: rc.local
    dest: /etc/rc.local
    owner: root
    group: root
    mode: 0700

- name: deploy rc-local unit file
  copy:
    src: rc-local.service
    dest: /etc/systemd/system/

- name: systemd daemon reload
  systemd:
    daemon_reload: yes

- name: enable and start systemd service
  systemd:
    name: rc-local.service
    state: restarted
  changed_when: false

