#!/bin/bash

## mouse works to resize the panes
## also for pane selection

# this works _perfectly_ on tmux 1.9
# on 2.6 however it fucking doesnt

tmux ls | grep 'system' > /dev/null || (
	tmux new-session -d -s 'system' -n 'stats' "sudo htop"
	#tmux split-window -p70\; send-keys "sudo journalctl -f -n10000" C-m
	tmux split-window -p70\; send-keys "sudo lnav" C-m
	tmux split-window -h "sudo iostat -xzdm 1"
	tmux split-window -v -p70\; send-keys "sudo iotop" C-m
	tmux split-window -p50 "sudo nload -u m -U H -i 102400 -o 102400 -a 60 $(grep $(hostname -I | cut -d' ' -f1) <(ip a) -B2  | head -1 | cut -d ':' -f2 | sed 's/ //g')"
	tmux select-pane -t 1
	tmux set-option -t 'system' mouse-resize-pane on
	tmux set-option -t 'system' mouse-select-pane on
	tmux bind-key C-b kill-session -t 'system'
)
exec tmux attach -t 'system'

