---

## devilspie2 ###############################################################################################
- name: install devilspie2 so lua scripts for window actions work to get transparent background to vscode
  apt:
    cache_valid_time: 7200
    name:
      - devilspie2

- name: ensure config folder exists
  file:
    dest: /home/sjas/.config/devilspie2/
    state: directory
    owner: sjas
    group: sjas

- name: deploy devilspie2 systemd unit file
  copy:
    src: devilspie2.service
    dest: /home/sjas/.config/systemd/user/
    owner: sjas
    group: sjas

- name: systemd daemon reload
  become: true
  become_user: sjas
  systemd:
    daemon_reload: yes
    scope: user

- name: enable and start systemd service
  become: true
  become_user: sjas
  systemd:
    name: devilspie2.service
    scope: user
    state: restarted
  changed_when: false

- name: deploy vscode transparent background config via devilspie
  copy:
    src: vscode.lua
    dest: /home/sjas/.config/devilspie2/
    mode: 0644

## vscode ###################################################################################################
- name: microsoft apt-key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: microsoft vscode repo
  apt_repository:
    repo: deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main
    state: present
    filename: vscode

- name: install vscode package
  apt:
    name: code
    state: present
    update_cache: yes

- name: vscode extension install check
  become: true
  become_user: sjas
  ignore_errors: true
  shell: |
    code --list-extensions | grep -i \
    -e albert.tabout \
    -e alireza94.theme-gotham \
    -e DavidAnson.vscode-markdownlint \
    -e dbaeumer.vscode-eslint \
    -e EFanZh.graphviz-preview \
    -e foxundermoon.shell-format \
    -e gizak.shortcuts \
    -e grapecity.gc-excelviewer \
    -e jamiewoodio.junos \
    -e jebbs.plantuml \
    -e jpogran.puppet-vscode \
    -e korekontrol.saltstack \
    -e LuxHackers.can-openr \
    -e matthias-schwarze.vimter \
    -e mechatroner.rainbow-csv \
    -e mitaki28.vscode-clang \
    -e ms-python.python \
    -e ms-vscode.cpptools \
    -e redhat.vscode-yaml \
    -e Rubymaniac.vscode-direnv \
    -e ryanolsonx.zenburn \
    -e ryu1kn.partial-diff \
    -e samuelcolvin.jinjahtml \
    -e thracian.theme-badwolf-paradox \
    -e wwm.better-align \
    -e yhirose.FilterText \
    -e Yummygum.city-lights-icon-vsc \
    | wc -l
  register: vsc_plugin_count
  changed_when: false

- name: set current vscode plugin count
  command: echo 27
  register: vsc_plugin_count_desired
  changed_when: false

- name: stop vscode because microsoft cant build software properly
  shell: pkill -9 code && echo 0 || echo 1
  register: vscode_stopped
  ignore_errors: true
  when: not vsc_plugin_count.stdout is search( "{{ vsc_plugin_count_desired.stdout }}" )
  changed_when: false

- name: install vscode extensions if not present
  become: true
  become_user: sjas
  command: code --force --install-extension {{ item }}
  with_items:
    - albert.tabout
    - alireza94.theme-gotham
    - DavidAnson.vscode-markdownlint
    - dbaeumer.vscode-eslint
    - efanzh.graphviz-preview
    - foxundermoon.shell-format
    - gizak.shortcuts
    - grapecity.gc-excelviewer
    - jamiewoodio.junos
    - jebbs.plantuml
    - jpogran.puppet-vscode
    - korekontrol.saltstack
    - LuxHackers.can-openr
    - matthias-schwarze.vimter
    - mechatroner.rainbow-csv
    - mitaki28.vscode-clang
    - ms-python.python
    - ms-vscode.cpptools
    - redhat.vscode-yaml
    - Rubymaniac.vscode-direnv
    - ryanolsonx.zenburn
    - ryu1kn.partial-diff
    - samuelcolvin.jinjahtml
    - thracian.theme-badwolf-paradox
    - wwm.better-align
    - yhirose.FilterText
    - Yummygum.city-lights-icon-vsc
  when: not vsc_plugin_count.stdout is search( "{{ vsc_plugin_count_desired.stdout }}" )
  tags: dont_lint_this

- name: set vscode configuration
  become: true
  become_user: sjas
  copy:
    src: settings.json
    dest: /home/sjas/.config/Code/User/settings.json

- name: set vscode keybindings for code navigation
  become: true
  become_user: sjas
  copy:
    src: keybindings.json
    dest: /home/sjas/.config/Code/User/

- name: start vscode if it was stopped
  become: true
  become_user: sjas
  command: code
  delegate_to: localhost
  when: not vsc_plugin_count.stdout is search("{{ vsc_plugin_count_desired.stdout }}") and vscode_stopped.stdout == "0"
  changed_when: false
