---

# zulu: https://docs.azul.com/core/zulu-openjdk/install/debian#install-from-azul-apt-repository
# temurin: https://adoptium.net/blog/2021/12/eclipse-temurin-linux-installers-available/
- name: eclipse adoptium apt signing key
  apt_key:
    url: "https://packages.adoptium.net/artifactory/api/gpg/key/public"
    state: present
    keyring: /etc/apt/keyrings/adoptium.gpg

- name: adoptium repo
  apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/adoptium.gpg] https://packages.adoptium.net/artifactory/deb noble main
    state: present
    filename: adoptium

- name: Install temurin java 23
  apt:
    name: "temurin-23-jdk"
    state: latest
    update_cache: true
